In [2]:
import scipy.io as sio
import numpy as np

In [4]:
# filename = "DAW_data_12_25_with_rewards.mat"
filename = "data/DAW_data_2_25_alpha_1.mat"
data = sio.loadmat(filename)
data_array = data['data'][0][0]

In [5]:
task = data_array['simulationfunction']
bounds = data_array['bounds']
sd = data_array['sd']
n_choices = data_array['choices']
reward_rate = data_array['rewardrate']
alpha = data_array['alpha']
beta = data_array['beta']
lam = data_array['lambda']
all_trials_data = data_array['simulationData']
rewards = data_array['rewards']
best_R1 = np.array([np.argmax(trial[0,:]) for trial in rewards])

In [6]:
np.shape(all_trials_data)

(100, 11, 10000, 4)

In [12]:
# Data in all_trials data is:
# nSimulation, w value, ntrials, [R1, R2 ,RW, S2]
# we only care about one simulation for each w value
# trials_data = all_trials_data[0,:,:,:]
trials_data = all_trials_data
# w value, ntrials, [R1, R2 ,RW, S2]
w_vals = np.arange(0,1.1,.1)
simulation_dict = {}


for w_idx, w in enumerate(w_vals):
    
    simulation_dict[w] = {
    "R1" : trials_data[:,w_idx,:,0],
    "S2" : trials_data[:,w_idx,:,3],
    "R2" : trials_data[:,w_idx,:,1],
    "Rw" : trials_data[:,w_idx,:,2],
    "best_R1" : best_R1
    }
    
    
# np.save('DAW_DATA_DICT_2_sims.npy', simulation_dict) 

np.save('data/DAW_DATA_100_sims_BROAD_REWARDS_alpha_1.npy', simulation_dict)

In [9]:
# Load
read_dictionary = np.load('data/DAW_DATA_for_cluster.npy').item()
np.shape(read_dictionary[0]['best_R1'])

(10000,)

In [17]:
np.unique(read_dictionary[0]['best_R1'])

array([0, 1])

In [11]:
alpha

array([[1]], dtype=uint8)

In [91]:
task

array(['MBMF_stochastic_2choices_p_sim'], dtype='<U30')

In [93]:

bounds


array([[0.25, 0.75]])

In [92]:
sd

array([[0.025]])

# Actual Subject Data

In [16]:
data_filename = "data/subject_data.mat"
fits_filename = "data/subject_fits.mat"
interaction_filename = "data/interaction.mat"
maineffect_filename = "data/maineffect.mat"
common_filename = "data/common.mat"

subject_data = sio.loadmat(data_filename)
subject_fits = sio.loadmat(fits_filename)
subject_interaction = sio.loadmat(interaction_filename)
subject_maineffect = sio.loadmat(maineffect_filename)
subject_common = sio.loadmat(common_filename)

In [17]:
np.shape(subject_common['common_S2'])

(197, 125)

In [18]:
np.shape((subject_data['human_data']))

(197, 125, 3)

In [26]:
trial_data = np.zeros((197,125,4))
trial_data[:,:,:3] = subject_data['human_data']
trial_data[:,:,3] = subject_common['common_S2']

In [ ]:
np.shape(trial_data)

In [5]:
np.shape((subject_interaction['subject_interaction']))

(197, 1)

In [28]:
human_dict = {
    'trial_data': trial_data,
    'subject_fits': subject_fits['subject_w_fits'],
    'interaction': subject_interaction['subject_interaction'],
    'maineffect': subject_maineffect['subject_maineffect']
}

In [29]:
np.save('DAW_human_data.npy', human_dict)

In [23]:
read_dictionary = np.load('DAW_human_data.npy').item()
np.shape(read_dictionary['subject_fits'])

(197, 1)

In [14]:
task

array(['MBMF_stochastic_2choices_p_sim'], dtype='<U30')